### ISSUE TITLE
Cannot launch HyperspyUI with latest master

### ISSUE THREAD

**Issue by jat255** [vidartf/hyperspyUI#19]
Hi Vidar,

I just tried to launch HyperspyUI with the latest hyperspy and hyperspyui master branches, and I'm getting an error. It seems to be related to traits/ipython, but I'm not sure what might be broken.

Here's the traceback:
```python
D:\UMD_Research\SOFC_Project\data\2015-01-30-YMdAP-02 EDS>python D:\UMD_Research\Software\hyperspyUI\hyperspyui\launch.py
C:\Python279-x64\lib\site-packages\sklearn\lda.py:4: DeprecationWarning: lda.LDA has been moved to discriminant_analysis.LinearDiscriminantAnalysis in 0.17 and will be removed in 0.19
  "in 0.17 and will be removed in 0.19", DeprecationWarning)
C:\Python279-x64\lib\site-packages\sklearn\qda.py:4: DeprecationWarning: qda.QDA has been moved to discriminant_analysis.QuadraticDiscriminantAnalysis in 0.17 and will be removed in 0.19.
  "in 0.17 and will be removed in 0.19.", DeprecationWarning)
d:\umd_research\software\hyperspyui\hyperspyui\pluginmanager.py:93: RuntimeWarning: Exception in import of hyperspyui plugin "segmentation" error:
  File "d:\umd_research\software\hyperspyui\hyperspyui\plugins\segmentation.py", line 5, in <module>
    from hyperspyui.tools import MultiSelectionTool
ImportError: cannot import name MultiSelectionTool

  self.warn("import", plug)
d:\umd_research\software\hyperspyui\hyperspyui\pluginmanager.py:93: RuntimeWarning: Exception in import of hyperspyui plugin "navigatorswitch" error:
  File "d:\umd_research\software\hyperspyui\hyperspyui\plugins\navigatorswitch.py", line 2, in <module>
    import hyperspy.roi
ImportError: No module named roi

  self.warn("import", plug)
d:\umd_research\software\hyperspyui\hyperspyui\pluginmanager.py:93: RuntimeWarning: Exception in import of hyperspyui plugin "align" error:
  File "d:\umd_research\software\hyperspyui\hyperspyui\plugins\align.py", line 7, in <module>
    from hyperspyui.tools import SelectionTool
ImportError: cannot import name SelectionTool

  self.warn("import", plug)
d:\umd_research\software\hyperspyui\hyperspyui\pluginmanager.py:93: RuntimeWarning: Exception in import of hyperspyui plugin "croptool" error:
  File "d:\umd_research\software\hyperspyui\hyperspyui\plugins\croptool.py", line 13, in <module>
    from hyperspy.roi import BaseInteractiveROI
ImportError: No module named roi

  self.warn("import", plug)
d:\umd_research\software\hyperspyui\hyperspyui\pluginmanager.py:93: RuntimeWarning: Exception in import of hyperspyui plugin "moviesaver" error:
  File "d:\umd_research\software\hyperspyui\hyperspyui\plugins\moviesaver.py", line 18, in <module>
    writers = mpl.animation.writers
AttributeError: 'module' object has no attribute 'animation'

  self.warn("import", plug)
d:\umd_research\software\hyperspyui\hyperspyui\pluginmanager.py:93: RuntimeWarning: Exception in import of hyperspyui plugin "linemeasure" error:
  File "d:\umd_research\software\hyperspyui\hyperspyui\plugins\linemeasure.py", line 11, in <module>
    from hyperspy.roi  import BaseInteractiveROI
ImportError: No module named roi

  self.warn("import", plug)
d:\umd_research\software\hyperspyui\hyperspyui\pluginmanager.py:93: RuntimeWarning: Exception in import of hyperspyui plugin "gaussianfilter" error:
  File "d:\umd_research\software\hyperspyui\hyperspyui\plugins\gaussianfilter.py", line 3, in <module>
    from hyperspy.signal import DataIterator
ImportError: cannot import name DataIterator

  self.warn("import", plug)
d:\umd_research\software\hyperspyui\hyperspyui\pluginmanager.py:93: RuntimeWarning: Exception in import of hyperspyui plugin "fitting" error:
  File "d:\umd_research\software\hyperspyui\hyperspyui\plugins\fitting.py", line 14, in <module>
    from hyperspyui.tools import SelectionTool
ImportError: cannot import name SelectionTool

  self.warn("import", plug)
Traceback (most recent call last):
  File "D:\UMD_Research\Software\hyperspyUI\hyperspyui\launch.py", line 93, in <module>
    main()
  File "D:\UMD_Research\Software\hyperspyUI\hyperspyui\launch.py", line 79, in main
    form = MainWindow()
  File "d:\umd_research\software\hyperspyui\hyperspyui\mainwindow.py", line 62, in __init__
    super(MainWindow, self).__init__(parent)
  File "d:\umd_research\software\hyperspyui\hyperspyui\mainwindowlayer5.py", line 97, in __init__
    super(MainWindowLayer5, self).__init__(parent)
  File "d:\umd_research\software\hyperspyui\hyperspyui\mainwindowlayer4.py", line 23, in __init__
    super(MainWindowLayer4, self).__init__(parent)
  File "d:\umd_research\software\hyperspyui\hyperspyui\mainwindowlayer3.py", line 24, in __init__
    super(MainWindowLayer3, self).__init__(parent)
  File "d:\umd_research\software\hyperspyui\hyperspyui\mainwindowlayer2.py", line 31, in __init__
    super(MainWindowLayer2, self).__init__(parent)
  File "d:\umd_research\software\hyperspyui\hyperspyui\mainwindowlayer1.py", line 133, in __init__
    self.create_ui()
  File "d:\umd_research\software\hyperspyui\hyperspyui\mainwindowlayer1.py", line 219, in create_ui
    self.create_console()
  File "d:\umd_research\software\hyperspyui\hyperspyui\mainwindowlayer1.py", line 484, in create_console
    control = ConsoleWidget(config=c)
  File "d:\umd_research\software\hyperspyui\hyperspyui\widgets\consolewidget.py", line 21, in __init__
    super(ConsoleWidget, self).__init__(*args, **kwargs)
  File "C:\Python279-x64\lib\site-packages\IPython\qt\console\rich_ipython_widget.py", line 39, in __init__
    super(RichIPythonWidget, self).__init__(*args, **kw)
  File "C:\Python279-x64\lib\site-packages\IPython\qt\console\ipython_widget.py", line 118, in __init__
    super(IPythonWidget, self).__init__(*args, **kw)
  File "C:\Python279-x64\lib\site-packages\IPython\qt\console\frontend_widget.py", line 155, in __init__
    super(FrontendWidget, self).__init__(*args, **kw)
  File "C:\Python279-x64\lib\site-packages\IPython\qt\console\history_console_widget.py", line 27, in __init__
    super(HistoryConsoleWidget, self).__init__(*args, **kw)
  File "C:\Python279-x64\lib\site-packages\IPython\qt\console\console_widget.py", line 245, in __init__
    LoggingConfigurable.__init__(self, **kw)
  File "C:\Python279-x64\lib\site-packages\IPython\config\configurable.py", line 80, in __init__
    self.config = config
  File "C:\Python279-x64\lib\site-packages\IPython\utils\traitlets.py", line 430, in __set__
    new_value = self._validate(obj, value)
  File "C:\Python279-x64\lib\site-packages\IPython\utils\traitlets.py", line 451, in _validate
    return self.validate(obj, value)
  File "C:\Python279-x64\lib\site-packages\IPython\utils\traitlets.py", line 965, in validate
    self.error(obj, value)
  File "C:\Python279-x64\lib\site-packages\IPython\utils\traitlets.py", line 798, in error
    raise TraitError(e)
IPython.utils.traitlets.TraitError: The 'config' trait of a ConsoleWidget instance must be a Config or None, but a value of class 'traitlets.config.loader.Config' (i.e. {'FrontendWidget': {'banner': u'\n    H y p e r S p y\n    Version 0.9+dev\n\n    http://www.hyperspy.org\n\n    '}}) was specified.
```

For reference, here's my installation environment (via `pip list`)
```python
agpy (0.1.4)
alabaster (0.7.6)
apptools (4.3.0)
APScheduler (3.0.4)
astropy (1.0.6)
autopep8 (1.2.1)
Babel (2.1.1)
backports-abc (0.4)
backports.ssl-match-hostname (3.4.0.2)
BeautifulSoup (3.2.1)
beautifulsoup4 (4.4.1)
brewer2mpl (1.4.1)
certifi (2015.11.20)
cffi (1.3.1)
characteristic (14.3.0)
cloud (2.8.5)
cmd2 (0.6.8)
colorama (0.3.3)
configobj (5.0.6)
cryptography (1.1.1)
cssselect (0.9.1)
cycler (0.9.0)
Cython (0.23.4)
DateTime (4.0.1)
decorator (4.0.5)
display (1.0.0)
distribute (0.7.3)
Django (1.8.6)
docopt (0.6.2)
docutils (0.12)
enum34 (1.0.4)
envisage (4.4.0)
Flask (0.10.1)
frosted (1.4.1)
functools32 (3.2.3.post2)
future (0.15.2)
futures (3.0.3)
Ghost.py (0.2.3)
h5py (2.5.0)
hyperspy (0.7.3-113-gbdba301, d:\umd_research\software\hyperspy)
hyperspy-tools (0.1.0, d:\umd_research\software\hyperspy_tools)
hyperspyUI (0.5, d:\umd_research\software\hyperspyui)
idna (2.0)
ipaddress (1.0.15)
ipnb (0.1.0)
ipykernel (4.2.1)
ipython (3.2.3)
ipython-genutils (0.1.0)
itsdangerous (0.24)
jedi (0.9.0)
Jinja2 (2.8)
jsonschema (2.5.1)
jupyter-client (4.1.1)
jupyter-core (4.0.6)
keyring (5.6)
libtiff (0.4.0)
lxml (3.5.0)
MarkupSafe (0.23)
matplotlib (1.4.0)
mayavi (4.4.3)
MDP (3.3)
measurement (1.8.0)
mechanize (0.2.5)
memory-profiler (0.39)
mistune (0.7.1)
montage-wrapper (0.9.9.dev235, d:\umd_research\software\montage-wrapper)
mpldatacursor (0.6.1)
mpltools (0.2.0)
myfitnesspal (1.5, c:\users\josh\builds\python-myfitnesspal)
networkx (1.10)
nose (1.3.7)
numpy (1.10.1)
numpydoc (0.5)
ordereddict (1.1)
pandas (0.17.1)
path.py (8.1.2)
patsy (0.4.1)
pep8 (1.6.2)
pickleshare (0.5)
pies (2.6.7)
pies2overrides (2.6.7)
Pillow (3.0.0)
pip (7.1.2)
pkginfo (1.2.1)
plotly (1.9.0)
prettyplotlib (0.1.7)
progressbar (2.3, d:\umd_research\software\python-progressbar)
psutil (3.2.2)
py (1.4.30)
pyasn1 (0.1.9)
pyasn1-modules (0.0.8)
pycairo-gtk (1.10.0)
pycparser (2.14)
pycrypto (2.6.1)
pycurl (7.19.5.3)
pyenchant (1.6.6)
pyface (5.0.0)
Pyfig (0.1)
pyflakes (1.0.0)
Pygments (2.0.2)
pygobject (2.28.6)
pygtk (2.22.0)
PyInstaller (3.0)
PyOpenGL (3.1.0)
pyOpenSSL (0.15.1)
pyparsing (2.0.6)
pyqode.core (2.7.0)
pyqode.python (2.7.0)
pyqode.qt (2.7.0)
PyQwt (5.2.1)
pyreadline (2.1)
pyregion (1.1.4)
PySide (1.2.4)
pytest (2.8.3)
python-dateutil (2.4.2)
python-qt-binding (0.2.14)
pytz (2015.7)
PyV8 (1.0)
PyVTK (0.4.85)
pywin32 (218)
pyzmq (15.1.0)
queuelib (1.4.2)
requests (2.8.1)
requests-toolbelt (0.5.0)
rodeo (0.4.4)
scikit-fmm (0.0.7)
scikit-image (0.11.3)
scikit-learn (0.17)
scipy (0.16.1)
Scrapy (1.0.3)
seaborn (0.6.dev0, d:\umd_research\software\seaborn)
selenium (2.48.0)
service-identity (14.0.0)
setuptools (18.6)
simplegeneric (0.8.1)
singledispatch (3.4.0.3)
six (1.10.0)
snowballstemmer (1.2.0)
Sphinx (1.3.1)
sphinx-bootstrap-theme (0.4.8)
sphinx-rtd-theme (0.1.9)
spyder (2.3.7)
statsmodels (0.6.1)
sympy (0.7.6.1)
tifffile (0.7.0)
tornado (4.3)
tpbcalcs (0.1.0)
traitlets (4.0.0)
traits (4.5.0)
traitsui (4.5.1)
triangle (2015.3.28)
twill (0.9)
twine (1.6.4)
Twisted (15.4.0)
tzlocal (1.2)
vispy (0.5.0.dev0, d:\umd_research\software\python\vispy)
VTK (6.1.0)
w3lib (1.13.0)
Werkzeug (0.11.2)
wheel (0.26.0)
yolk (0.4.3)
zope.interface (4.1.3)
```

**Comment by jat255** [comment]
Brilliant! Thanks for that. Sorry to bother you with that. Seems to be working well!
