### ISSUE TITLE
HyperspyUI will not start with matplotlib==1.5

### ISSUE THREAD

**Issue by jat255** [vidartf/hyperspyUI#20]
As it says in the title. HyperspyUI looks for `FigureCanvas`, which apparently doesn't exist in `1.5`:

```python
D:\UMD_Research\SOFC_Project\data\2015-01-30-YMdAP-02 EDS>python D:\UMD_Research\Software\hyperspyUI\hyperspyui\launch.py
C:\Python279-x64\lib\site-packages\sklearn\lda.py:4: DeprecationWarning: lda.LDA has been moved to discriminant_analysis.LinearDiscriminantAnalysis in 0.17 and will be removed in 0.19
  "in 0.17 and will be removed in 0.19", DeprecationWarning)
C:\Python279-x64\lib\site-packages\sklearn\qda.py:4: DeprecationWarning: qda.QDA has been moved to discriminant_analysis.QuadraticDiscriminantAnalysis in 0.17 and will be removed in 0.19.
  "in 0.17 and will be removed in 0.19.", DeprecationWarning)
Traceback (most recent call last):
  File "D:\UMD_Research\Software\hyperspyUI\hyperspyui\launch.py", line 93, in <module>
    main()
  File "D:\UMD_Research\Software\hyperspyUI\hyperspyui\launch.py", line 77, in main
    from hyperspyui.mainwindow import MainWindow
  File "d:\umd_research\software\hyperspyui\hyperspyui\mainwindow.py", line 16, in <module>
    from hyperspyui.mainwindowlayer5 import MainWindowLayer5, tr
  File "d:\umd_research\software\hyperspyui\hyperspyui\mainwindowlayer5.py", line 32, in <module>
    from hyperspyui.mdi_mpl_backend import FigureCanvas
ImportError: cannot import name FigureCanvas
```

**Comment by vidartf** [comment]
Yeah, since I'm relying on the internals of matplotlib (not its documented API), I have to manually check and support for every new version. I guess I could just let the default behavior be to assume latest version, and try with that.

**Comment by vidartf** [comment]
Should be fixed in latest.

**Comment by jat255** [comment]
Works for me! Thanks!
